import type { ThemeColorRef } from "./types";

function colorRef<Token extends ThemeColorRef["token"]>(token: Token): ThemeColorRef<Token> {
	return table.freeze({ kind: "themeColor", token });
}

export const theme = table.freeze({
	primary: table.freeze({
		main: colorRef("primary.main"),
		light: colorRef("primary.light"),
		dark: colorRef("primary.dark"),
		contrast: colorRef("primary.contrast"),
	}),
	secondary: table.freeze({
		main: colorRef("secondary.main"),
		light: colorRef("secondary.light"),
		dark: colorRef("secondary.dark"),
		contrast: colorRef("secondary.contrast"),
	}),
	error: table.freeze({
		main: colorRef("error.main"),
		light: colorRef("error.light"),
		dark: colorRef("error.dark"),
		contrast: colorRef("error.contrast"),
	}),
	warning: table.freeze({
		main: colorRef("warning.main"),
		light: colorRef("warning.light"),
		dark: colorRef("warning.dark"),
		contrast: colorRef("warning.contrast"),
	}),
	info: table.freeze({
		main: colorRef("info.main"),
		light: colorRef("info.light"),
		dark: colorRef("info.dark"),
		contrast: colorRef("info.contrast"),
	}),
	success: table.freeze({
		main: colorRef("success.main"),
		light: colorRef("success.light"),
		dark: colorRef("success.dark"),
		contrast: colorRef("success.contrast"),
	}),
	text: table.freeze({
		primary: colorRef("text.primary"),
		secondary: colorRef("text.secondary"),
		disabled: colorRef("text.disabled"),
		inverse: colorRef("text.inverse"),
	}),
	background: table.freeze({
		default: colorRef("background.default"),
		surface: colorRef("background.surface"),
	}),
	border: table.freeze({
		subtle: colorRef("border.subtle"),
		default: colorRef("border.default"),
		strong: colorRef("border.strong"),
	}),
	action: table.freeze({
		hover: colorRef("action.hover"),
		pressed: colorRef("action.pressed"),
		disabled: colorRef("action.disabled"),
		disabledBackground: colorRef("action.disabledBackground"),
	}),
	palette: table.freeze({
		gray: table.freeze({
			"0": colorRef("palette.gray.0"),
			"1": colorRef("palette.gray.1"),
			"2": colorRef("palette.gray.2"),
			"3": colorRef("palette.gray.3"),
			"4": colorRef("palette.gray.4"),
			"5": colorRef("palette.gray.5"),
			"6": colorRef("palette.gray.6"),
			"7": colorRef("palette.gray.7"),
			"8": colorRef("palette.gray.8"),
			"9": colorRef("palette.gray.9"),
		}),
		primary: table.freeze({
			"0": colorRef("palette.primary.0"),
			"1": colorRef("palette.primary.1"),
			"2": colorRef("palette.primary.2"),
			"3": colorRef("palette.primary.3"),
			"4": colorRef("palette.primary.4"),
			"5": colorRef("palette.primary.5"),
			"6": colorRef("palette.primary.6"),
			"7": colorRef("palette.primary.7"),
			"8": colorRef("palette.primary.8"),
			"9": colorRef("palette.primary.9"),
		}),
		red: table.freeze({
			"0": colorRef("palette.red.0"),
			"1": colorRef("palette.red.1"),
			"2": colorRef("palette.red.2"),
			"3": colorRef("palette.red.3"),
			"4": colorRef("palette.red.4"),
			"5": colorRef("palette.red.5"),
			"6": colorRef("palette.red.6"),
			"7": colorRef("palette.red.7"),
			"8": colorRef("palette.red.8"),
			"9": colorRef("palette.red.9"),
		}),
		green: table.freeze({
			"0": colorRef("palette.green.0"),
			"1": colorRef("palette.green.1"),
			"2": colorRef("palette.green.2"),
			"3": colorRef("palette.green.3"),
			"4": colorRef("palette.green.4"),
			"5": colorRef("palette.green.5"),
			"6": colorRef("palette.green.6"),
			"7": colorRef("palette.green.7"),
			"8": colorRef("palette.green.8"),
			"9": colorRef("palette.green.9"),
		}),
		yellow: table.freeze({
			"0": colorRef("palette.yellow.0"),
			"1": colorRef("palette.yellow.1"),
			"2": colorRef("palette.yellow.2"),
			"3": colorRef("palette.yellow.3"),
			"4": colorRef("palette.yellow.4"),
			"5": colorRef("palette.yellow.5"),
			"6": colorRef("palette.yellow.6"),
			"7": colorRef("palette.yellow.7"),
			"8": colorRef("palette.yellow.8"),
			"9": colorRef("palette.yellow.9"),
		}),
		blue: table.freeze({
			"0": colorRef("palette.blue.0"),
			"1": colorRef("palette.blue.1"),
			"2": colorRef("palette.blue.2"),
			"3": colorRef("palette.blue.3"),
			"4": colorRef("palette.blue.4"),
			"5": colorRef("palette.blue.5"),
			"6": colorRef("palette.blue.6"),
			"7": colorRef("palette.blue.7"),
			"8": colorRef("palette.blue.8"),
			"9": colorRef("palette.blue.9"),
		}),
	}),
});
